version: '3.7'
services:
  backend:
    image: node:18-alpine
    working_dir: /web/backend
    volumes:
      - ./web:/web
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm install nodemon && npx nodemon api.js"
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=oniricuser
      - POSTGRES_PASSWORD=saturno
      - POSTGRES_DB=magnabase
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: